import React from "react";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import logo from "../public/logo.jpg";
import bg1 from "../public/bg1.jpg";
import about from "../public/about.jpg";
import { GiHamburgerMenu } from "react-icons/gi";
import Head from "next/head";
import { BsFacebook, BsFillTelephoneFill } from "react-icons/bs";
import { BsInstagram } from "react-icons/bs";
import { FaFacebook } from "react-icons/fa";
import { AiFillCiCircle, AiFillCloseCircle } from "react-icons/ai";

function About() {
  const [nav, setNav] = useState(true);
  const HandleNav = () => {
    setNav(!nav);
  };
  return (
    <main className="about">
      <div>
        <title>Mondi Clean - Dubinsko Pranje</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </div>
      <nav className="relative mx-auto p-6">
        <div className="flex items-center justify-between ">
          <a href="." className="text-3xl  font-bold flex-row flex">
            <Image
              src={logo}
              alt={"logo"}
              className="h-9 w-9 scale-150 mr-6 mobileview:hidden"
            />
            MondiClean
          </a>

          <div className="space-x-6 mx-auto hamburgermax:hidden lgview:mr-[46rem] tview:mr-64">
            <a
              onClick={() => window.open("aboutus", "_self")}
              className="hover:text-gray-500 mx-auto"
            >
              Više O Nama
            </a>
            <a
              onClick={() => window.open("galerija", "_self")}
              className="hover:text-gray-500"
            >
              Galerija
            </a>
          </div>
          <div onClick={HandleNav}>
            {!nav ? (
              <AiFillCloseCircle className="text-2xl hamburger:hidden focus:out justify-end items-end ml-32" />
            ) : (
              <GiHamburgerMenu className="hamburger:hidden focus:out justify-end items-end text-2xl ml-32" />
            )}
          </div>
          <div
            id="hamburger"
            className={
              !nav
                ? "fixed left-0 top-0 w-[60%] h-full shadow-xl bg-gray-800 text-white z-50 m ease-in-out duration-500"
                : "fixed left-[-100%]"
            }
          >
            {" "}
            <ul className=" uppercase">
              <a href="." className="pt-6 p-2 flex text-3xl  font-bold ">
                MondiClean
              </a>
              <li
                onClick={() => window.open("aboutus", "_self")}
                className="hover:text-gray-500 p-4 border-b border-white pt-24 "
              >
                Više O Nama
              </li>
              <li
                onClick={() => window.open("galerija", "_self")}
                className="hover:text-gray-500 p-4 border-b border-white   "
              >
                Galerija
              </li>
              <li
                onClick={() => window.open("kontakt", "_self")}
                className="hover:text-gray-500 p-4 border-b  border-white  "
              >
                Kontakt
              </li>
            </ul>
          </div>
          <div>
            <a
              onClick={() => window.open("kontakt", "_self")}
              className="md:block p-3 px-6 pt-2 text-white rounded-full bg-blue-500 hover:bg-blue-400 hamburgermax:hidden "
            >
              Kontakt
            </a>
          </div>
        </div>
      </nav>
      <header>
        <h1 className="text-6xl font-bold text-black z-40 flex justify-center py-12">
          Ko smo mi?
        </h1>
        <div>
          <Image
            src={bg1}
            className="h-[19rem] w-[25rem] flex  mx-auto object-cover "
            alt={"mondiclean1"}
          />
          <div className="bg-blue-500 -mt-48 pt-48"></div>
        </div>
        <div className="bg-blue-500">
          <div className="bg-blue-500  text-white p-12   block flex-col font-md max-w-[30rem]  mx-auto  ">
            <p>
              Mondi Clean se bavi dubinskim pranjem i čišćenjem vozila,
              nameštaja, dušeka, jastuka, stolica, tepiha...
              <br></br> Posle 5 godina poslovanja i iskustva trudimo se što
              kvalitetnije da oradimo posao. <br></br>Radimo se profesionalnim
              KARCHER mašinama i koristimo najkvalitetnija sredstva za čišćenje
              da bi postigli vrhunske rezultate usluga koje pružimo:
            </p>
            <li>Izlazimo na adresu na pranje</li>
            <li>Nudimo povoljne cene i kvalitetnu uslogu</li>
            <li>
              Ima mogućnosti za povolnije cene i stalne muštenije, restorana,
              hotele, apartmane
            </li>
          </div>
        </div>
      </header>

      <section>
        <footer className="bg-gray-800">
          <div className="container flex flex-col-reverse justify-between px-6 py-10 mx-auto space-y-8 mdview:flex-row mdview:space-y-0">
            <div className="flex flex-col-reverse items-center justify-between space-y-12 md:flex-col mdview:space-y-0 mdview:items-start">
              <div className="mx-auto  text-center text-white md:hidden">
                <a href="." className="text-4xl font-bold ">
                  Mondi Clean<br></br>
                </a>
                Copyright &copy; 2022, All Rights Reserved:<br></br>
                <a
                  href="https://www.linkedin.com/in/attilaxfeher/"
                  className="hover:text-blue-300"
                  target="_blank"
                  rel="noreferrer"
                >
                  Attila Feher
                </a>
                <div className="flex flex-wrap gap-12 items-center justify-center mt-4 text-xl ">
                  <a
                    href="https://www.facebook.com/profile.php?id=100057332714848"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <BsFacebook className="hover:text-blue-300" />
                  </a>
                  <a
                    href="https://www.instagram.com/mondiclean/"
                    target="_blank"
                    rel="noreferrer"
                  >
                    <BsInstagram className="hover:text-blue-300" />
                  </a>
                  <a href="tel:063-8449334">
                    <BsFillTelephoneFill className="hover:text-blue-300" />
                  </a>
                </div>
              </div>
              <div></div>
              <div className="flex justify-center space-x-4"></div>
            </div>
            ={" "}
            <div className="flex justify-around space-x-32">
              <div className="flex flex-col space-y-3 text-white">
                <a href="#" className="hover:text-blue-100">
                  Home
                </a>
                <a href="#" className="hover:text-blue-100">
                  Pricing
                </a>
                <a href="#" className="hover:text-blue-100">
                  Products
                </a>
                <a href="#" className="hover:text-blue-100">
                  About
                </a>
              </div>
              <div className="flex flex-col space-y-3 text-white">
                <a href="#" className="hover:text-blue-100">
                  Careers
                </a>
                <a href="#" className="hover:text-blue-100">
                  Community
                </a>
                <a href="#" className="hover:text-blue-100">
                  Privacy Policy
                </a>
              </div>
            </div>
            <div className="flex flex-col justify-between">
              <form>
                <div className="flex space-x-3"></div>
              </form>
            </div>
          </div>
        </footer>
      </section>
    </main>
  );
}

export default About;
