import React from "react";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import Image from "next/image";
import logo from "../public/logo.jpg";
import bg1 from "../public/bg1.jpg";
import about from "../public/about.jpg";
import { GiHamburgerMenu } from "react-icons/gi";
import Head from "next/head";
import { AiFillCiCircle, AiFillCloseCircle } from "react-icons/ai";
import { BsFacebook, BsFillTelephoneFill } from "react-icons/bs";
import { BsInstagram } from "react-icons/bs";
import { FaFacebook } from "react-icons/fa";
import galerija1 from "../public/galerija/mondigalerija.jpg";
import galerija2 from "../public/galerija/mondigalerija2.jpg";
import galerija3 from "../public/galerija/mondigalerija3.jpg";
import galerija4 from "../public/galerija/mondigalerija4.jpg";
import galerija5 from "../public/galerija/mondigalerija5.jpg";
import galerija6 from "../public/galerija/mondigalerija6.jpg";
import galerija7 from "../public/galerija/mondigalerija7.jpg";
import galerija8 from "../public/galerija/mondigalerija8.jpg";
import galerija9 from "../public/galerija/mondigalerija9.jpg";
import galerija10 from "../public/galerija/mondigalerija10.jpg";
import galerija11 from "../public/galerija/mondigalerija11.jpg";
import galerija12 from "../public/galerija/mondigalerija12.jpg";
import galerija14 from "../public/galerija/mondigalerija13.jpg";
import galerija15 from "../public/galerija/mondigalerija14.jpg";
import galerija16 from "../public/galerija/mondigalerija15.jpg";
import galerija17 from "../public/galerija/mondigalerija16.jpg";
import galerija18 from "../public/galerija/mondigalerija17.jpg";
import galerija19 from "../public/galerija/mondigalerija18.jpg";
import galerija20 from "../public/galerija/mondigalerija19.jpg";
import galerija21 from "../public/galerija/mondigalerija20.jpg";
import galerija22 from "../public/galerija/mondigalerija21.jpg";
import galerija23 from "../public/galerija/mondigalerija22.jpg";
import galerija24 from "../public/galerija/mondigalerija23.jpg";
import galerija25 from "../public/galerija/mondigalerija24.jpg";
import galerija26 from "../public/galerija/mondigalerija25.jpg";
import galerija27 from "../public/galerija/mondigalerija26.jpg";
import galerija28 from "../public/galerija/mondigalerija27.jpg";
import galerija29 from "../public/galerija/mondigalerija28.jpg";
import galerija30 from "../public/galerija/mondigalerija29.jpg";
import galerija31 from "../public/galerija/mondigalerija30.jpg";
import galerija32 from "../public/galerija/mondigalerija31.jpg";
import galerija33 from "../public/galerija/mondigalerija32.jpg";
import galerija34 from "../public/galerija/mondigalerija33.jpg";
import galerija35 from "../public/galerija/mondigalerija34.jpg";
import galerija36 from "../public/galerija/mondigalerija35.jpg";
import galerija37 from "../public/galerija/mondigalerija37.jpg";

function Galerija() {
  const [nav, setNav] = useState(true);
  const HandleNav = () => {
    setNav(!nav);
  };
  return (
    <main>
      <Head>
        <title>Mondi Clean - Dubinsko Pranje</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="relative mx-auto p-6">
        <div className="flex items-center justify-between ">
          <a href="." className="text-3xl  font-bold flex-row flex">
            <Image
              src={logo}
              alt={"logo"}
              className="h-9 w-9 scale-150 mr-6 mobileview:hidden"
            />
            MondiClean
          </a>

          <div className="space-x-6 mx-auto hamburgermax:hidden lgview:mr-[46rem] tview:mr-64">
            <a
              onClick={() => window.open("aboutus", "_self")}
              className="hover:text-gray-500 mx-auto"
            >
              Više O Nama
            </a>
            <a
              onClick={() => window.open("galerija", "_self")}
              className="hover:text-gray-500"
            >
              Galerija
            </a>
          </div>
          <div onClick={HandleNav}>
            {!nav ? (
              <AiFillCloseCircle className="text-2xl hamburger:hidden focus:out justify-end items-end ml-32" />
            ) : (
              <GiHamburgerMenu className="hamburger:hidden focus:out justify-end items-end text-2xl ml-32" />
            )}
          </div>
          <div
            id="hamburger"
            className={
              !nav
                ? "fixed left-0 top-0 w-[60%] h-full shadow-xl bg-gray-800 text-white z-50 m ease-in-out duration-500"
                : "fixed left-[-100%]"
            }
          >
            {" "}
            <ul className=" uppercase">
              <a href="." className="pt-6 p-2 flex text-3xl  font-bold ">
                MondiClean
              </a>
              <li
                onClick={() => window.open("aboutus", "_self")}
                className="hover:text-gray-500 p-4 border-b border-white pt-24 "
              >
                Više O Nama
              </li>
              <li
                onClick={() => window.open("galerija", "_self")}
                className="hover:text-gray-500 p-4 border-b border-white   "
              >
                Galerija
              </li>
              <li
                onClick={() => window.open("kontakt", "_self")}
                className="hover:text-gray-500 p-4 border-b  border-white  "
              >
                Kontakt
              </li>
            </ul>
          </div>
          <div>
            <a
              onClick={() => window.open("kontakt", "_self")}
              className="md:block p-3 px-6 pt-2 text-white rounded-full bg-blue-500 hover:bg-blue-400 hamburgermax:hidden "
            >
              Kontakt
            </a>
          </div>
        </div>
      </nav>
      <header
        className="object-cover h-[40rem] w-[60rem] 
          flex-row mx-auto justify-center      gap-1 mt-64 grid grid-rows-4 grid-flow-col scale-150 
      tview:flex-col mb-64 mobileview:grid-cols-10 
      tview:h-[20rem] tview:w-[16rem] "
      >
        <Image src={galerija1} alt={"mondigalerija1"} />
        <Image src={galerija2} alt={"mondigalerija2"} />
        <Image src={galerija3} alt={"mondigalerija3"} />
        <Image src={galerija4} alt={"mondigalerija4"} />

        <Image src={galerija5} alt={"mondigalerija5"} />
        <Image src={galerija6} alt={"mondigalerija6"} />
        <Image src={galerija7} alt={"mondigalerija7"} />
        <Image src={galerija8} alt={"mondigalerija8"} />
        <Image src={galerija9} alt={"mondigalerija9"} />
        <Image src={galerija10} alt={"mondigalerija10"} />
        <Image src={galerija11} alt={"mondigalerija11"} />
        <Image src={galerija12} alt={"mondigalerija12"} />
        <Image src={galerija14} alt={"mondigalerija13"} />
        <Image src={galerija15} alt={"mondigalerija14"} />
        <Image src={galerija16} alt={"mondigalerija15"} />
        <Image src={galerija17} alt={"mondigalerija16"} />
        <Image src={galerija18} alt={"mondigalerija17"} />
        <Image src={galerija20} alt={"mondigalerija18"} />
        <Image src={galerija21} alt={"mondigalerija20"} />
        <Image src={galerija22} alt={"mondigalerija22"} />
        <Image src={galerija23} alt={"mondigalerija23"} />
        <Image src={galerija24} alt={"mondigalerija24"} />
        <Image src={galerija25} alt={"mondigalerija25"} />
        <Image src={galerija26} alt={"mondigalerija26"} />
        <Image src={galerija27} alt={"mondigalerija27"} />
        <Image src={galerija28} alt={"mondigalerija28"} />
        <Image src={galerija29} alt={"mondigalerija29"} />
        <Image src={galerija30} alt={"mondigalerija30"} />
        <Image src={galerija31} alt={"mondigalerija31"} />
        <Image src={galerija32} alt={"mondigalerija32"} />
        <Image src={galerija33} alt={"mondigalerija33"} />
        <Image src={galerija36} alt={"mondigalerija35"} />
      </header>
      <footer className="bg-gray-800">
        <div className="container flex flex-col-reverse justify-between px-6 py-10 mx-auto space-y-8 mdview:flex-row mdview:space-y-0">
          <div className="flex flex-col-reverse items-center justify-between space-y-12 md:flex-col mdview:space-y-0 mdview:items-start">
            <div className="mx-auto  text-center text-white md:hidden">
              <a href="." className="text-4xl font-bold ">
                Mondi Clean<br></br>
              </a>
              Copyright &copy; 2022, All Rights Reserved:<br></br>
              <a
                href="https://www.linkedin.com/in/attilaxfeher/"
                className="hover:text-blue-300"
                target="_blank"
                rel="noreferrer"
              >
                Attila Feher
              </a>
              <div className="flex flex-wrap gap-12 items-center justify-center mt-4 text-xl ">
                <a
                  href="https://www.facebook.com/profile.php?id=100057332714848"
                  target="_blank"
                  rel="noreferrer"
                >
                  <BsFacebook className="hover:text-blue-300" />
                </a>
                <a
                  href="https://www.instagram.com/mondiclean/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <BsInstagram className="hover:text-blue-300" />
                </a>
                <a href="tel:063-8449334">
                  <BsFillTelephoneFill className="hover:text-blue-300" />
                </a>
              </div>
            </div>
            <div></div>
            <div className="flex justify-center space-x-4"></div>
          </div>
          ={" "}
          <div className="flex justify-around space-x-32">
            <div className="flex flex-col space-y-3 text-white">
              <a href="#" className="hover:text-blue-100">
                Home
              </a>
              <a href="#" className="hover:text-blue-100">
                Pricing
              </a>
              <a href="#" className="hover:text-blue-100">
                Products
              </a>
              <a href="#" className="hover:text-blue-100">
                About
              </a>
            </div>
            <div className="flex flex-col space-y-3 text-white">
              <a href="#" className="hover:text-blue-100">
                Careers
              </a>
              <a href="#" className="hover:text-blue-100">
                Community
              </a>
              <a href="#" className="hover:text-blue-100">
                Privacy Policy
              </a>
            </div>
          </div>
          <div className="flex flex-col justify-between">
            <form>
              <div className="flex space-x-3"></div>
            </form>
          </div>
        </div>
      </footer>
    </main>
  );
}

export default Galerija;
