import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BiTime } from "react-icons/bi";
import { ImPriceTag } from "react-icons/im";
import { BiWrench } from "react-icons/bi";
import { BsFacebook, BsFillTelephoneFill } from "react-icons/bs";
import { BsInstagram } from "react-icons/bs";
import { GiHamburgerMenu } from "react-icons/gi";
import { FaFacebook } from "react-icons/fa";
import { AiFillCiCircle, AiFillCloseCircle } from "react-icons/ai";

import illustration from "../public/illustration.jpg";
import servis from "../public/servis.jpg";
import logo from "../public/logo.jpg";
import servis2 from "../public/servis2.jpg";
import bg1 from "../public/bg1.jpg";
import kristijan from "../public/kristijan.jpg";
import stanislav from "../public/stanislav.jpg";
import ratko from "../public/ratko.jpg";

export default function Home() {
  const [nav, setNav] = useState(true);
  const HandleNav = () => {
    setNav(!nav);
  };
  return (
    <div>
      <Head>
        <title>Mondi Clean - Dubinsko Pranje</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <nav className="relative mx-auto p-6">
          <div className="flex items-center justify-between ">
            <a href="." className="text-3xl  font-bold flex-row flex">
              <Image
                src={logo}
                alt={"logo"}
                className="h-9 w-9 scale-150 mr-6 mobileview:hidden"
              />
              MondiClean
            </a>

            <div className="space-x-6 mx-auto hamburgermax:hidden lgview:mr-[46rem] tview:mr-64">
              <a
                onClick={() => window.open("aboutus", "_self")}
                className="hover:text-gray-500 mx-auto"
              >
                Više O Nama
              </a>
              <a
                onClick={() => window.open("galerija", "_self")}
                className="hover:text-gray-500"
              >
                Galerija
              </a>
            </div>
            <div onClick={HandleNav}>
              {!nav ? (
                <AiFillCloseCircle className="text-2xl hamburger:hidden focus:out justify-end items-end ml-32" />
              ) : (
                <GiHamburgerMenu className="hamburger:hidden focus:out justify-end items-end text-2xl ml-32" />
              )}
            </div>
            <div
              id="hamburger"
              className={
                !nav
                  ? "fixed left-0 top-0 w-[60%] h-full shadow-xl bg-gray-800 text-white z-50 m ease-in-out duration-500"
                  : "fixed left-[-100%]"
              }
            >
              {" "}
              <ul className=" uppercase">
                <a href="." className="pt-6 p-2 flex text-3xl  font-bold ">
                  MondiClean
                </a>
                <li
                  onClick={() => window.open("aboutus", "_self")}
                  className="hover:text-gray-500 p-4 border-b border-white pt-24 "
                >
                  Više O Nama
                </li>
                <li
                  onClick={() => window.open("galerija", "_self")}
                  className="hover:text-gray-500 p-4 border-b border-white   "
                >
                  Galerija
                </li>
                <li
                  onClick={() => window.open("kontakt", "_self")}
                  className="hover:text-gray-500 p-4 border-b  border-white  "
                >
                  Kontakt
                </li>
              </ul>
            </div>
            <div>
              <a
                onClick={() => window.open("kontakt", "_self")}
                className="md:block p-3 px-6 pt-2 text-white rounded-full bg-blue-500 hover:bg-blue-400 hamburgermax:hidden "
              >
                Kontakt
              </a>
            </div>
          </div>
        </nav>

        <section id="hero" className="overflow-hidden">
          <div className="w-100 tview:mb-40">
            <Image
              src={bg1}
              className="z-40 absolute brightness-50 mdview:h-[40rem]  object-cover mdview:w-full tview:h-1/2 "
              alt={"mondiclean"}
            />
            <div className=" flex flex-col md:flex-row items-center px-6 mx-auto space-y-0 z-30 text-white view:h-10 ">
              <div className="flex flex-col lgview:mb-12 space-y-4 md:w-1/2 z-40 text-color mobileview:mt-32 mt-52 tview:mt-32">
                <h1 className="text-4xl font-bold text-center mdview:text-6xl ">
                  Dubinsko Pranje
                </h1>
                <p className="max-w-sm text-center md:text-left">
                  Želite da vaši stvari izgledaju kao nove? Obravite nam se za
                  dubinsko pranje i čisćenje.
                </p>
                <div className="flex justify-center md:justify-start">
                  <a
                    onClick={() => window.open("kontakt", "_self")}
                    className="md:block p-3 px-6 pt-2 text-white bg-brightRed rounded-full baseline bg-blue-500 hover:bg-blue-300 "
                  >
                    Kontakt
                  </a>
                </div>
              </div>
            </div>
          </div>
          <h3 className="text-4xl  text-center font-bold mt-64 mb-4 tview:mt-2">
            Dubinsko Pranje
          </h3>
        </section>
        <section id="usluge" className="flex flex-row">
          <div className="flex mobileview:flex-col px-6 justify-center mx-auto text-center gap-16">
            <div className="flex flex-col mobileview">
              <Image
                src={servis}
                className="mdview:scale-75 h-64 w-64 md:transform-none  self-center rounded-lg"
                alt={""}
              />
              <h2 className="py-4 font-semibold text-4xl mt-4">
                Servis za čisćenje
              </h2>
              <p className="max-w-xs mx-auto mdview:mt-6 ">
                Bavimo se{" "}
                <span className="text-blue-500">
                  dubinsko pranjem i čistenjem{" "}
                </span>
                svih vrsta vozila, nameštaja, dušeka, jastuka, stolica i tepiha,
                održavanjem i čistenjem lokala, garni hotela, čisćenje tvrđih
                podova.
              </p>
            </div>
            <div className="flex flex-col place-items">
              <Image
                src={servis2}
                className="mdview:scale-75 h-64 w-64 md:transform-none  self-center rounded-lg"
                alt={""}
              />
              <h2 className="py-4 font-semibold text-4xl">
                Zašto je pranje <br></br>nameštaja bitno?
              </h2>
              <p className="max-w-xs mx-auto">
                Nameštaj je veoma pogodno sto za više vrsta štotcina koje mi ni
                ne vidimo, a koji nam mogu napraviti ozbiljne probleme. Posle{" "}
                <span className="text-blue-500">
                  profesionalnog pranja nameštaja
                </span>{" "}
                ne samo da će biti kao novi, nego će biti očišćeno od grinja,
                bakterija i raznih nečistoća.
              </p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <div className="containerw  md:flex-row items-center px-6 mx-auto mt-10 space-y-0 md:space-y-0">
              <h3 className="text-4xl  text-center font-bold mb-6">
                Zašto smo najbolji?
              </h3>
              <p className=" py-1 text-center max-w-sm mx-auto">
                Sa više <span className="text-blue-500">godišnjem </span>{" "}
                iskustvom, cilj nam je da našim klijentima nudimo{" "}
                <span className="text-blue-500"> stalan kvalitet </span> usluga
                na najvišem njivou.
              </p>
            </div>
          </div>
          <div className="lgview:flex flex-row    max-w-xl gap-12 mx-auto justify-center ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white">
              <BiTime className="text-8xl mx-auto text-blue-500" />
              <h3 className="text-lg font-medium pt-8 pb-2 lgview:w-52">
                Brzo Sušenje
              </h3>
              <p className="py-2">
                Sušenje vršimo u specijalnoj komori za sušenje tepiha, koja je
                opremnjena jakim ventilatorima, kaloriferom i skuplječem vage.
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <ImPriceTag className="text-8xl mx-auto text-blue-500" />
              <h3 className="text-lg font-medium pt-8 pb-2 lgview:w-52">
                Povoljne Cene
              </h3>
              <p className="py-2">
                Po pristupačnim cenama nudimo najviši kvalitet.
              </p>
            </div>
            <div className="text-center shadow-lg p-10  rounded-xl my-10 dark:bg-white flex-1">
              <BiWrench className="text-8xl mx-auto text-blue-500" />
              <h3 className="text-lg font-medium pt-8 pb-2 lgview:w-52">
                Professionalna Oprema
              </h3>
              <p className="py-2">
                Za sve naše usluge koje pružamo koristimo profesionalne mašine
                sa kombinacijom vrhunskih hemija.
              </p>
            </div>
          </div>
        </section>

        <section id="testimonials">
          <div className=" px-5 mx-auto mt-8 justify-center text-center tview:overflow-hidden">
            <h2 className="text-4xl font-bold text-center mb-6">
              Šta Ljudi Misle O Nama?
            </h2>
            <p className=" text-center max-w-sm mx-auto ">
              Tokom dugogodišnjeg iskustva stekli smo puno zadovoljnih
              mušterija.
            </p>
            <div className="max-w-sm m-auto justify-center gap-10 pb-12 text-white shadow-3xl lgview:flex  ">
              <div className="flex flex-col mt-24 md:flex-row md:space-x-6">
                <div className="flex flex-col items-center p-6 space-y-6 rounded-3xl  md:w-1/3 shadow-2xl bg-blue-500 px-20">
                  <Image
                    src={stanislav}
                    className="w-32 h-[8rem] -mt-14 rounded-3xl object-cover"
                    alt={""}
                  />
                  <h5 className="text-lg align-top font-bold">
                    Stanislav Cvetkovic
                  </h5>
                  <p className="w-52 text-white pb-36">
                    Brzo i efikasno odrađen posao! Sve preporuke!
                  </p>
                </div>
              </div>
              <div className="flex flex-col mt-24 md:flex-row md:space-x-6">
                <div className="flex flex-col items-center p-6 space-y-6 rounded-3xl  md:w-1/3 shadow-2xl bg-blue-500 px-20">
                  <Image
                    src={kristijan}
                    className="w-32 -mt-14 rounded-3xl "
                    alt={""}
                  />
                  <h5 className="text-lg font-bold  ">Kristijan Černjak</h5>
                  <p className="w-52 text-white">
                    Veoma precizano i detaljano obavljeno dubinsko ciscenje
                    nasih vozila i namestaja . U najsitnije detalje ocisceno ,
                    vade sedista iz vozila .... EXTRA KVALITET USLUGA !!! ZA
                    SVAKU PREPORUKU !!! CISTA 10KA
                  </p>
                </div>
              </div>

              <div className="flex flex-col mt-24 md:flex-row md:space-x-6">
                <div className="flex flex-col items-center p-6 space-y-6 rounded-3xl  md:w-1/3 shadow-2xl bg-blue-500 px-20 ">
                  <Image
                    src={ratko}
                    className="w-32 -mt-14 rounded-3xl alt="
                    alt={""}
                  />
                  <h5 className="text-lg font-bold ">Ratko Latinković </h5>
                  <p className="text-white w-52 pb-36">
                    Sve preporuke! Prezadovoljan!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="cta" className="bg-blue-500">
          <div className="container flex flex-col items-center justify-between px-6 mx-auto space-y-12 md:flex-row pb-6">
            <h2 className="text-4xl font-bold text-center text-white mobileview:text-4xl mt-6 -mb-6">
              Najjedostavniji Servis
            </h2>

            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2801.3078147611695!2d19.885829015791476!3d45.40313207910017!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475b3d28f1e2d221%3A0x537917427b574c16!2sMondi%20Clean!5e0!3m2!1sen!2srs!4v1670923460313!5m2!1sen!2srs"
              width="600"
              height="450"
              className="hamburgermax:w-64 hamburgermax:h-64  mobileview:h-64 mobileview:w-64  "
            ></iframe>
            <a
              onClick={() => window.open("kontakt", "_self")}
              className="p-3 px-6 pt-2 text-blue-500 rounded-full  bg-white hover:bg-gray-200 "
            >
              Kontakt
            </a>
          </div>
        </section>

        <section>
          <footer className="bg-gray-800">
            <div className="container flex flex-col-reverse justify-between px-6 py-10 mx-auto space-y-8 mdview:flex-row mdview:space-y-0">
              <div className="flex flex-col-reverse items-center justify-between space-y-12 md:flex-col mdview:space-y-0 mdview:items-start">
                <div className="mx-auto  text-center text-white md:hidden">
                  <a href="." className="text-4xl font-bold ">
                    Mondi Clean<br></br>
                  </a>
                  Copyright &copy; 2022, All Rights Reserved:<br></br>
                  <a
                    href="https://www.linkedin.com/in/attilaxfeher/"
                    className="hover:text-blue-300"
                    target="_blank"
                    rel="noreferrer"
                  >
                    Attila Feher
                  </a>
                  <div className="flex flex-wrap gap-12 items-center justify-center mt-4 text-xl ">
                    <a
                      href="https://www.facebook.com/profile.php?id=100057332714848"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <BsFacebook className="hover:text-blue-300" />
                    </a>
                    <a
                      href="https://www.instagram.com/mondiclean/"
                      target="_blank"
                      rel="noreferrer"
                    >
                      <BsInstagram className="hover:text-blue-300" />
                    </a>
                    <a href="tel:063-8449334">
                      <BsFillTelephoneFill className="hover:text-blue-300" />
                    </a>
                  </div>
                </div>
                <div></div>
                <div className="flex justify-center space-x-4"></div>
              </div>
              ={" "}
              <div className="flex justify-around space-x-32">
                <div className="flex flex-col space-y-3 text-white">
                  <a href="#" className="hover:text-blue-100">
                    Home
                  </a>
                  <a href="#" className="hover:text-blue-100">
                    Pricing
                  </a>
                  <a href="#" className="hover:text-blue-100">
                    Products
                  </a>
                  <a href="#" className="hover:text-blue-100">
                    About
                  </a>
                </div>
                <div className="flex flex-col space-y-3 text-white">
                  <a href="#" className="hover:text-blue-100">
                    Careers
                  </a>
                  <a href="#" className="hover:text-blue-100">
                    Community
                  </a>
                  <a href="#" className="hover:text-blue-100">
                    Privacy Policy
                  </a>
                </div>
              </div>
              <div className="flex flex-col justify-between">
                <form>
                  <div className="flex space-x-3"></div>
                </form>
              </div>
            </div>
          </footer>
        </section>
      </main>
    </div>
  );
}
